### ISSUE TITLE
Menu autotags not working in GL 2.1.1

### ISSUE THREAD

**Issue by spacequad** [Geeklog-Plugins/menu#1]
Installed menu plugin v1.2.5 and everything appeared to install okay.  Then I made the changes for the header.thtml file and it worked.  Then I continued to test and create the block menu, and it failed to work after configuring it.  When I created the block menu with the autotag [menu:block] in the normal block, the block shows up as type only.  So to run a test further, I used the phpblock_getMenu(block) directly and the block finally showed up, however, the flyouts, were under the center content block when hovering.  Possible CSS issue.  I even installed the autotags plugin, thinking that may have had something to do with the autotags not working, but it made no difference.

**Comment by mystralkk** [comment]
I am not sure when this bug was fixed, but I have confirmed it is already fixed with v1.2.8.
