### ISSUE TITLE
Add support for newer Geeklog API

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/menu#3]
New way to access templates (supports child templates)
- $topicnavbar = COM_newTemplate(CTL_plugin_templatePath('forum'));

For redirects
- echo COM_refresh to COM_redirect($_CONF['site_url'] . '/calendar/index.php');

Use the Geeklog Input Class
- New Input instead of com_stripslashes, etc.. - example  $page = (int) Geeklog\Input::fPost('cpage', 0);)

DB_escapeString
- = DB_escapeString($pid);

Add the use of remove4byteUtf8Chars for submitted text to support the config option remove_4byte_chars
- $message = GLText::remove4byteUtf8Chars($message); #

**Comment by mystralkk** [comment]
Fixed with changeset 8158067.
